[firebase]
type = "service_account"
project_id = "zeeshan-s-hygiene-checklist"
private_key_id = "24f4964114b5432a0ba0dc96710840b9552ad9d9"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCKJI49IC4kyQb1
2g3OIhsQNMRhoO0C6kXdNy2fQLWPEUBJ1I2MJbjbht86SRkBsZmYC3K0hKQq0D9o
VlNrO+LRgxw9vg8gmKA47EzbOoM3wjMUKiplJieBCiAwJ40OD3TZbEtiM3jbGDM3
Q+cXUc73fkmQo4yd+cBQl375iYboAz+o8+92CHhMdhBLhgbJj+yIyQXPFE1nsDWD
GU5/pBM3l9muap4udeU9BRbtFr6cD45BajVQ8x2Y3hnW1QV0k+S5zlEJ9ldtfFQE
JDraFETed1DL+J75Yb8rQUA/2QrQsRDTFIAzRVPWiQ2/Me38hyLyGijmBuYLoAQ7
Z4i9ticFAgMBAAECggEACWr8l4Y+HxvlcZVwI4GHvs8aJF3ISs6V/MLqRVUwC5Tt
gRsQm2Fm/PBw/5RENC1bf1Yod84jMxgHeqGIBmOKzyXVIxB2D47YPYk+pCOVFpQS
z2kggszbHJ0IHMBViYPcP4Z2jTddIfLAayAh/SECrzTY5xd/WrXQOq5ZZcHOhLq6
T9zvbDExLfwbNPnZxFdoK8eXLe00eKr0Xgo+ookqL4w0QxcG5oRZ5qNI40+SdnB0
6aidCOoy324v8h9N/dfZIcJkhbie8nVVKeqNogSNWxNn8z3F13aRN9a3PqgdlOtu
2PyZVmuhxbgmZ9qNpr7iUgN67kGKQ279A01KBC3pcQKBgQDC5W/fH/zpvGTLmk3c
/6eADMkgXjR9b8o/TE4js9JFEyPPx+x38qwX4V9HXKiglZbHS4h6r1KPwxvlPXBJ
qQ2F3hYsr9mxySVLPnLIr/QjMrpRhvO7BWqbeSgIJzd6sQp0SA5MA9nNksgWQn8x
iahvsFV9tZmp9Ib4NpjOB5M7/wKBgQC1dAgdkHPB8osga0HcbXqdWPKpxAvoYkXu
XWBUATswbA0lNr+VEh6TqUYJ25OaIOPYBzZfjqYREJk3j5TbIK0pXbHSwWiywh43
zFsRpRKlPpo3f1zV5uDekrQzbxIUTeNb44V/agkxY4AZorAg/JRiEulIxOlsZH2i
O64cB/Ws+wKBgETEV9jOnJqMUrRUWazkt+FCoaS+GJ851o7HCbsnM8YTnsstq44X
Hgm/B7NSSl1+6pifWiSPv/3hxfH436nd8FuPpRtXYOSOKI6IFlAhZW8V8w/ZIh6X
Jqp88VcPH1A3L40f74t6wFr8s4THKcH85GWkPkYA0ZtaIFVsTjZEDftZAoGAIa27
o+Ef2yutbwL5YnRfgbz0rVXZ7/PtjuR98JmZ5s7nUbTrsjt+uWF9wm6i4sSgBYSx
LuNHJ3uxNILN2i4idb8SNk/3otYszaZ8cLX20/zemtZk4L7NlgIcuD8xV9ttC60b
Jh8EPcp+CEQN9NFsqRdhfUQvHxM3zljNZB6GFukCgYBNi9QVD38xaCqmbLHLZRXK
+IPhQggNTY8UJB1/YOctgXp8ACFHkvsWtR+Sfh/Kz8IX1ZA1vmxKgwhh8Kx4Vt33
Ik1ezUeciRY2XxYj5RzANhXNH7qE+ZcGNeQTIBT41C4xw8fn2futkXo0bEfzBUra
A/E9EAXA2XOgkqQFkRI8PQ==
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@zeeshan-s-hygiene-checklist.iam.gserviceaccount.com"
client_id = "100560723037845840687"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40zeeshan-s-hygiene-checklist.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[imgbb]
api_key = "08b53a28b8374832a8ea6c5f20048423"
